Use fast-glob instead of glob
To fix :
node_modules/@types/glob/index.d.ts:29:42 - error TS2694: Namespace '"U:/VisualStudioCode/Projects/vscode-extension-case-search/vscode-extension-case-incremental-search/node_modules/minimatch/dist/cjs/index"' has no exported member 'IOptions'.

29     interface IOptions extends minimatch.IOptions {
                                            ~~~~~~~~

node_modules/@types/glob/index.d.ts:74:30 - error TS2724: '"U:/VisualStudioCode/Projects/vscode-extension-case-search/vscode-extension-case-incremental-search/node_modules/minimatch/dist/cjs/index"' has no exported member named 'IMinimatch'. Did you mean 'Minimatch'?

74         minimatch: minimatch.IMinimatch;
                                ~~~~~~~~~~